project:
  type: website
  output-dir: docs

website:
  title: "zaakeer_ahmad_m"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog
      # - href: posts/py_analysis/index.qmd
      #   text: py_analysis
      # - href: posts/r_analysis/index.qmd
      #   text: r_analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



